apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-microservice
  labels:
    app: home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: todos.azurecr.io/home-service:v1
        ports:
        - containerPort: 5002
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5002
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: home-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50