apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-microservice
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: mainservice.azurecr.io/main-service:v1
        ports:
        - containerPort: 5003
        env:
          - name: HOME_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: home-configmap
                key: service_url
          - name: WORK_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: work-configmap
                key: service_url
          - name: PERSONAL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: personal-configmap
                key: service_url
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: personal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5003