apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-microservice
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: todoapps.azurecr.io/main-service:v1
        ports:
        - containerPort: 5003
        env:
          - name: HOME_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: home-configmap
                key: service_url
          - name: WORK_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: work-configmap
                key: service_url
          - name: PERSONAL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: personal-configmap
                key: service_url
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: LoadBalancer
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50