apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-microservice
  labels:
    app: personal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
    spec:
      containers:
      - name: personal
        image: personalservice.azurecr.io/personal-service:v1
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: personal-service
spec:
  selector:
    app: personal
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: personal-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: personal
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50