apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-microservice
  labels:
    app: work
spec:
  replicas: 2
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: work
        image: todoapps.azurecr.io/work-service:1.0
        ports:
        - containerPort: 5001
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: work-service
spec:
  selector:
    app: work
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: work-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: work
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50